server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  port: 8180
spring:
  datasource:
#    url: jdbc:agensgraph://localhost:5430/postgres
    url: jdbc:postgresql://localhost:5430/postgres
    driver-class-name: org.postgresql.Driver
    username: hdseo
    password: 1234
    hikari:
#      connection-init-sql: set graph_path=crypto
      connection-test-query: SELECT 1
      maximum-pool-size: 5
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: mapper/*.xml
  type-aliases-package: com.crypto.model
logging:
  level:
    root: INFO
